version: '3'

services:
  web:
    container_name: theam-backend
    build: .
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nodeapp-network
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
      - "27017:27017" 
    networks:
      - nodeapp-network
networks:
  nodeapp-network:
    driver: bridge